export const initialArtists = [
    { nome: "Arisa", canzone: "Magica favola", img: "arisa.png" },
    { nome: "Bambole di pezza", canzone: "Resta con me", img: "bambole_di_pezza.png" },
    { nome: "Chiello", canzone: "Ti penso sempre", img: "chiello.png" },
    { nome: "Dargen D’Amico", canzone: "Ai ai", img: "dargen_d_amico.png" },
    { nome: "Ditonellapiaga", canzone: "Che fastidio!", img: "dito_nella_piaga.png" },
    { nome: "Eddie Brock", canzone: "Avvoltoi", img: "eddie_brock.png" },
    { nome: "Elettra Lamborghini", canzone: "Voilà", img: "elettra_lamborghini.png" },
    { nome: "Enrico Nigiotti", canzone: "Ogni volta che non so volare", img: "enrico_nigiotti.png" },
    { nome: "Ermal Meta", canzone: "Stella stellina", img: "ermal_meta.png" },
    { nome: "Fedez & Masini", canzone: "Male necessario", img: "fedez_&_masini.png" },
    { nome: "Francesco Renga", canzone: "Il meglio di me", img: "francesco_renga.png" },
    { nome: "Fulminacci", canzone: "Stupida sfortuna", img: "fulminacci.png" },
    { nome: "J-Ax", canzone: "Italia starter pack", img: "j-ax.png" },
    { nome: "LDA & Aka 7even", canzone: "Poesie clandestine", img: "lda_e_aka 7even.png" },
    { nome: "Leo Gassmann", canzone: "Naturale", img: "leo_gassmann.png" },
    { nome: "Levante", canzone: "Sei tu", img: "levante.png" },
    { nome: "Luchè", canzone: "Labirinto", img: "luche.png" },
    { nome: "Malika Ayane", canzone: "Animali notturni", img: "malika_ayane.png" },
    { nome: "Mara Sattei", canzone: "Le cose che non sai di me", img: "mara_sattei.png" },
    { nome: "Maria Antonietta & Colombre", canzone: "La felicità e basta", img: "maria_antonietta_&_colombre.png" },
    { nome: "Michele Bravi", canzone: "Prima o poi", img: "michele_bravi.png" },
    { nome: "Nayt", canzone: "Prima che", img: "nayt.png" },
    { nome: "Patty Pravo", canzone: "Opera", img: "patty_pravo.png" },
    { nome: "Raf", canzone: "Ora e per sempre", img: "raf.png" },
    { nome: "Sal Da Vinci", canzone: "Per sempre sì", img: "sal_da_vinci.png" },
    { nome: "Samurai Jay", canzone: "Un'altra estate", img: "samurai_jay.png" },
    { nome: "Sayf", canzone: "Sogni", img: "sayf.png" },
    { nome: "Serena Brancale", canzone: "Qui con me", img: "serena_brancale.png" },
    { nome: "Tommaso Paradiso", canzone: "I romantici", img: "tommaso_paradiso.png" },
    { nome: "Tredici Pietro", canzone: "Uomo che cade", img: "tredici_pietro.png" }
].map((data) => ({
    id: data.nome.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
    nome: data.nome,
    canzone: data.canzone,
    immagine: data.img,
    recensione_admin: "",
    voto_admin: 0,
    parola_chiave: "",
    is_published: false,
    published_at: null,
    user_votes: [],
    is_test: false
}));

// Add test artist
initialArtists.push({
    id: "peppe-vessicchio",
    nome: "Peppe Vessicchio",
    canzone: "Canzone di Prova",
    immagine: "peppe_vessicchio.png",
    recensione_admin: "Un maestro senza tempo",
    voto_admin: 10,
    parola_chiave: "Dirimpettaio",
    is_published: true,
    published_at: new Date(),
    user_votes: [],
    is_test: true
});
