export const initialArtists = [
    { nome: "Arisa", canzone: "La notte" },
    { nome: "Bambole di pezza", canzone: "Favole (mi hai rotto il cazzo)" },
    { nome: "Chiello", canzone: "Quanto ti vorrei" },
    { nome: "Dargen D’Amico", canzone: "Dove si balla" },
    { nome: "Ditonellapiaga", canzone: "Chimica" },
    { nome: "Eddie Brock", canzone: "Roma d'estate" },
    { nome: "Elettra Lamborghini", canzone: "Musica (e il resto scompare)" },
    { nome: "Enrico Nigiotti", canzone: "Nonno Hollywood" },
    { nome: "Ermal Meta", canzone: "Non mi avete fatto niente" },
    { nome: "Fedez & Masini", canzone: "Fottitene" },
    { nome: "Francesco Renga", canzone: "Il mio giorno più bello nel mondo" },
    { nome: "Fulminacci", canzone: "Santa Marinella" },
    { nome: "J-Ax", canzone: "Maria Salvador" },
    { nome: "LDA & Aka 7even", canzone: "Senza te" },
    { nome: "Leo Gassmann", canzone: "Terzo cuore" },
    { nome: "Levante", canzone: "Vivo" },
    { nome: "Luchè", canzone: "Star" },
    { nome: "Malika Ayane", canzone: "Come Foglie" },
    { nome: "Mara Sattei", canzone: "Duemilaminuti" },
    { nome: "Maria Antonietta & Colombre", canzone: "Sassi" },
    { nome: "Michele Bravi", canzone: "Il diario degli errori" },
    { nome: "Nayt", canzone: "Gli occhi della tigre" },
    { nome: "Patty Pravo", canzone: "Pazza idea" },
    { nome: "Raf", canzone: "Infinito" },
    { nome: "Sal Da Vinci", canzone: "Non riesco a farti innamorare" },
    { nome: "Samurai Jay", canzone: "Bye Bye" },
    { nome: "Sayf", canzone: "Kassav" },
    { nome: "Serena Brancale", canzone: "Baccalà" },
    { nome: "Tommaso Paradiso", canzone: "Non avere paura" },
    { nome: "Tredici Pietro", canzone: "Pizza e fichi" }
].map((data, index) => ({
    id: data.nome.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
    nome: data.nome,
    canzone: data.canzone,
    recensione_admin: "",
    voto_admin: 0,
    parola_chiave: "",
    is_published: false,
    published_at: null,
    user_votes: [],
    is_test: false
}));

// Add test artist
initialArtists.push({
    id: "peppe-vessicchio",
    nome: "Peppe Vessicchio",
    canzone: "Canzone di Prova",
    recensione_admin: "Un maestro senza tempo",
    voto_admin: 10,
    parola_chiave: "Dirimpettaio",
    is_published: true,
    published_at: new Date(),
    user_votes: [],
    is_test: true
});
